<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Domain\OnlineShop.Modules.Notification.Domain.csproj" />
    <ProjectReference Include="..\..\Ordering\Domain\OnlineShop.Modules.Ordering.Domain.csproj" />
    <ProjectReference Include="..\..\Inventory\Domain\OnlineShop.Modules.Inventory.Domain.csproj" />
    <ProjectReference Include="..\..\Ordering\Application\OnlineShop.Modules.Ordering.Application.csproj" />
    <ProjectReference Include="..\..\Catalog\Application\OnlineShop.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\Identity\Application\OnlineShop.Modules.Identity.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="12.4.1" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
